name: Container Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ARM64
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/masteredward/xavier:latest